import { useState } from "react";
import { api } from "../api";
import { notify } from "../components";
import { categoryLabel, relativeTime } from "../lib/format";
import { useAsync } from "../lib/hooks";
import type { DeliveryRow } from "../types";

/**
 * Shows the AI diagnosis for a failing delivery. Everything the model says is
 * framed as a likely cause with its evidence, next to the raw attempts it came
 * from, so a developer can check it instead of trusting it blindly.
 */
export default function DiagnosisPanel({ delivery, hasAttempts }: { delivery: DeliveryRow; hasAttempts: boolean }) {
  const { data: diag, reload } = useAsync(() => api.diagnosis(delivery.id), [delivery.id], 3000);
  const [busy, setBusy] = useState(false);

  const failing = delivery.status === "dead" || (delivery.status === "pending" && delivery.attempt_count > 0);
  if (diag === undefined) return null; // first load
  if (!diag && (!failing || !hasAttempts)) return null;

  async function diagnose() {
    setBusy(true);
    try {
      await api.diagnose(delivery.id);
      reload();
    } catch (e) {
      notify(e instanceof Error ? e.message : "Couldn't start the diagnosis.", "bad");
    } finally {
      setBusy(false);
    }
  }

  const button = (label: string) => (
    <button type="button" className="button-quiet" onClick={() => void diagnose()} disabled={busy}>
      {busy ? "Starting…" : label}
    </button>
  );

  if (!diag) {
    return (
      <section className="diagnosis" aria-labelledby="diag-title">
        <h2 id="diag-title">Why is this failing?</h2>
        <p className="muted">
          Get a likely cause and a suggested fix. A local AI model reads the recent attempts, with emails, tokens and
          other secrets removed first.
        </p>
        {button("Diagnose failure")}
      </section>
    );
  }

  if (diag.status === "pending" || diag.status === "running") {
    return (
      <section className="diagnosis" aria-labelledby="diag-title" aria-busy="true">
        <h2 id="diag-title">Diagnosing…</h2>
        <p className="muted">
          {diag.status === "pending" ? "Waiting for the diagnosis worker." : "The model is reading the attempts."} On a
          CPU this can take up to a minute.
        </p>
      </section>
    );
  }

  if (diag.status === "failed" || !diag.result) {
    return (
      <section className="diagnosis" aria-labelledby="diag-title">
        <h2 id="diag-title">The diagnosis didn't finish</h2>
        <p className="muted">{diag.note ?? "Something went wrong while analyzing this delivery."}</p>
        {button("Try again")}
      </section>
    );
  }

  const r = diag.result;
  const byRules = diag.model === "rules";
  return (
    <section className="diagnosis" aria-labelledby="diag-title">
      <div className="diagnosis-head">
        <div>
          <p className="diagnosis-kicker">Likely cause</p>
          <h2 id="diag-title">{categoryLabel[r.category] ?? r.category}</h2>
        </div>
        <span className={`confidence confidence-${r.confidence}`}>{r.confidence} confidence</span>
      </div>
      <p className="diagnosis-summary">{r.summary}</p>

      <dl className="diagnosis-body">
        <dt>What's going on</dt>
        <dd>{r.likely_cause}</dd>
        <dt>Suggested fix</dt>
        <dd>{r.suggested_fix}</dd>
        {r.evidence.length > 0 && (
          <>
            <dt>Based on</dt>
            <dd>
              <ul className="evidence">
                {r.evidence.map((e, i) => (
                  <li key={i}>
                    <code>{e}</code>
                  </li>
                ))}
              </ul>
            </dd>
          </>
        )}
      </dl>

      {diag.note && <p className="note note-warn">{diag.note}</p>}

      <div className="diagnosis-foot">
        <p className="hint">
          {byRules ? "Rule-based diagnosis." : `Generated by ${diag.model}${diag.cached ? " (reused from an identical failure)" : ""}.`}{" "}
          {!byRules && "AI can be wrong, so check it against the attempts below."} Diagnosed{" "}
          {relativeTime(diag.updated_at)}.
        </p>
        {button("Diagnose again")}
      </div>
    </section>
  );
}
